name: Run matrix
on:
  workflow_dispatch:
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.target }}
    steps:
      - uses: actions/github-script@v6
        id: matrix
        with:
          github-token: ${{ github.token }}
          script: |
            core.setOutput("target", {
              target: ["a", "b", "c"]
            })

  job:
    uses: ./.github/workflows/wrapped_job.yml
    name: Job ${{ matrix.target }}
    needs:
      - prepare
    strategy:
      matrix:
        target: [a, b, c]
    with:
      target: ${{ matrix.target }}
