name: Run matrix
on:
  workflow_dispatch:
jobs:
  job:
    uses: ./.github/workflows/wrapped_job.yml
    strategy:
      matrix:
        target: [a, b, c]
    with:
      target: ${{ matrix.target }}
